name: Frontend check build

on:
  pull_request:
    paths:
      - "frontend/**"
      - '!**.md'

defaults:
  run:
    working-directory: frontend

jobs:
  check-build:
    timeout-minutes: 5

    strategy:
      matrix:
        node-version: [16.17.0]
        os: [ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Composite Setup node
        uses: ./.github/actions/setup/node
        with:
          node-version: ${{ matrix.node-version }}
          work-directory: frontend

      - name: Build check
        run: yarn build
        env:
          MICRO_CMS_DOMAIN: ${{ secrets.MICRO_CMS_DOMAIN }}
          MICRO_CMS_API_KEY: ${{ secrets.MICRO_CMS_API_KEY }}
