name: Deploy CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: frontend

jobs:
  git-deploy:
    timeout-minutes: 5

    strategy:
      matrix:
        node-version: [18.17.1]
        os: [ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Composite Setup node
        uses: ./.github/actions/setup/node
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: yarn build
        env:
          NEXT_PUBLIC_STAGE: prod

      # しかしGitHub Pagesの仕様として_から始まるディレクトリが見えず404となる
      # つまりHTMLからJSを読み込めない
      # これを回避するために.nojekyllファイルをoutディレクトリに作る
      - name: add nojekyll
        run: touch ./out/.nojekyll

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
