name: Deploy CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  git-deploy:
    timeout-minutes: 5

    strategy:
      matrix:
        node-version: [18.17.1]
        os: [ubuntu-22.04]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Composite Setup node
        uses: ./.github/actions/setup/node
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: yarn build
        env:
          NEXT_PUBLIC_STAGE: prod

      # GitHub Pagesで.nojekyllファイルを追加する理由
      # GitHub Pages では、デフォルトで Jekyll という静的サイトジェネレータが使用される。
      # Jekyll は一部のファイルやディレクトリ（特に アンダースコア _ から始まるディレクトリ やファイル）を無視してしまう仕様がある
      # これを回避するために.nojekyllファイルをoutディレクトリに作る
      - name: add nojekyll
        run: touch ./out/.nojekyll

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
