name: Test frontend

on:
  pull_request:
    paths:
      - 'src/**'
      - .github/workflows/test_frontend.yml
      - '!**.md'

jobs:
  setup-node:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Composite Setup node
        id: setup-node
        uses: ./.github/actions/setup/node
        with:
          node-version: 18.17.1

  build-frontend:
    needs:
      - setup-node
    timeout-minutes: 5

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.17.1

      - name: Restore node modules
        uses: actions/cache@v3
        id: node_modules_cache_id
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-1-${{ hashFiles('**/yarn.lock') }}

      - name: Use .env
        run: |
          echo NEXT_PUBLIC_STAGE=local > .env

      - name: Build check
        run: yarn build

  test-frontend:
    needs:
      - setup-node

    timeout-minutes: 10

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.17.1

      - name: Restore node modules
        uses: actions/cache@v3
        id: node_modules_cache_id
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-1-${{ hashFiles('**/yarn.lock') }}

      
      - name: Use .env
        run: |
          echo NEXT_PUBLIC_STAGE=local > .env

      - uses: artiomtr/jest-coverage-report-action@v2
        with:
          working-directory: ./
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: yarn
          test-script: yarn jest:c

  lint-frontend:
    needs:
      - setup-node
    timeout-minutes: 10

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.17.1

      - name: Restore node modules
        uses: actions/cache@v3
        id: node_modules_cache_id
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-1-${{ hashFiles('**/yarn.lock') }}

      - name: Use .env
        run: |
          echo NEXT_PUBLIC_STAGE=local > .env

      - name: Type check
        working-directory: packages/frontend
        run: yarn c:type

      - name: Eslint check
        working-directory: packages/frontend
        run: yarn c:eslint

      - name: Stylelint check
        working-directory: packages/frontend
        run: yarn s:check

